### ISSUE TITLE
Search by Artist/Album name

### ISSUE THREAD

**Issue by graphixillusion** [PrajwalVandana/maestro-cli#10]
I think that a more advanced search system should be allowed like search by Artist/Album names.

**Suggestion** Implement advanced search in these scenarios:

1. maestro search cli command
2. Interactive search during play: press "a" to add a new song then "s" for search.

**Comment by PrajwalVandana** [comment]
in the works!

**Comment by PrajwalVandana** [comment]
By the way, to address (2), you can add a song by name with "a" (just hit "a" and type in a song name, if there is only one match found it will add the song)

(1) is in the works like i said

**Comment by PrajwalVandana** [comment]
Latest dev commit has filtering by album/artist/albumartist in `maestro list`, next commit (in few hrs) will allow similar filtering in `maestro play` as well

**Comment by PrajwalVandana** [comment]
done
