### ISSUE TITLE
Do not work "Volume Up" on Windows

### ISSUE THREAD

**Issue by HaTeEvery** [PrajwalVandana/maestro-cli#14]
When i press '[' volume going down but when press']' nothing happens. Tested on Win10 and Win11. Also nothing happens when i try press '{' and '}'.

**Comment by PrajwalVandana** [comment]
Yes this is an issue that’s been on my todo list for a while; unfortunately I don’t have a Windows to test on, but I have been trying to fix this. Hopefully will get it soon!

**Comment by PrajwalVandana** [comment]
Just some information, it's because `]` is used as an escape character for terminal sequences and the Windows version of `curses.getch()` specifically can't handle that, I guess

Looks like my only real choice is to port from `curses` to `blessed` and hope that works

**Comment by PrajwalVandana** [comment]
`blessed` does not support detecting SHIFT+UP/DOWN; I gave up and added `-/=` for volume and `_/+` for focus as alternatives for (`[/]` and `{/}`, respectively) in latest release

the originals still exist, but I guess they'll only work on non-Windows systems ...

**Comment by PrajwalVandana** [comment]
Found the relevant issue https://github.com/zephyrproject-rtos/windows-curses/issues/41
